# Habilita o console web para acessar via navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Configurações de conexão
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Exibe os comandos SQL no log
spring.jpa.hibernate.ddl-auto=create
spring.jackson.property-naming-strategy=SNAKE_CASE
logging.file.name=${user.home}/h2data/logs/import-json.log